### ISSUE TITLE
Autogenerate SWR keys

### ISSUE THREAD

**Issue by maxdeviant** [croutonn/graphql-codegen-plugin-typescript-swr#29]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Would you be open to adding an option to autogenerate SWR keys?

It seems that most of the time you can derive the SWR key using a combination of the hook name and the data being passed to it.

So instead of having to write out this:

```ts
const { data: { article }, mutate: mutateArticle } = sdk().useGetArticle(
  `UniqueKeyForTheRequest/${slug}`, { slug }, { initialData }
);
```

this option would generate the hooks with the keys built in. I envision it could look something like this:

```ts
useGetArticle(variables, config) {
  return useSWR(['useGetArticle', ...Object.values(variables)], () => sdk.GetArticle(variables), config);
}
```

and then the usage would look like this:

```
const { data: { article }, mutate: mutateArticle } = sdk().useGetArticle({ slug }, { initialData });
```

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I'd be happy to submit a PR for this.

**Comment by croutonn** [comment]
hmm, ​I considered the same idea as you in the past.
​However, the serialization function of useSWR has the problem of converting the value of each field of a variables object to a string by referring to the value of WeakMap when it is an array or an object, so that the keys will be different for objects of different instances even if they have the same value.

​On the other hand, `JSON.stringify` is very slow ...
​As a result, I think it's best to write manually.

​But in many cases, as you say, it's fine, so it's worth implementing as an option.
​I have time now so I can implement it right away.

**Comment by croutonn** [comment]
I just released the canary version. ​You can install it with the following command!

​```sh
​yarn add -D graphql-codegen-plugin-typescript-swr@next
​```

**Comment by maxdeviant** [comment]
Wow, thanks for the quick turnaround! I'll try this out and see how it works 😄
